services:
  caddy-proxy-manager:
    image: ghcr.io/iamd3vil/caddyproxymanager:latest
    container_name: caddy-proxy-manager
    ports:
      - "80:80"     # HTTP traffic
      - "443:443"   # HTTPS traffic
      - "8080:8080" # Proxy Manager Web UI
    volumes:
      - ./config:/config # Persistent config storage
      - ./data:/data     # Caddy data (certificates, etc.)
      - ./logs:/var/log  # Logs
    environment:
      # DNS Provider credentials (optional - can be configured via UI instead)
      # Only set these if you want to use the same credentials for all proxies
      # - CLOUDFLARE_API_TOKEN=your-api-token
      # - DO_AUTH_TOKEN=your-do-token
      # - DUCKDNS_TOKEN=your-duckdns-token
      # - HETZNER_API_TOKEN=your-hetzner-token
      # - GANDI_BEARER_TOKEN=your-gandi-token
      # - DNSIMPLE_API_ACCESS_TOKEN=your-dnsimple-token
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  config:
    driver: local
  data:
    driver: local
  logs:
    driver: local
